### ISSUE TITLE
i can`t run the project

### ISSUE THREAD

**Issue by felipeolvr** [eneiluj/nextcloud-webdav-filepicker#2]
your project in vue is not running with me, I can't run the project, how do i run the project ??

**Comment by julien-nc** [comment]
What do you mean?
* What are you trying to do in the end?
* Are you importing the npm package or trying to use it from the repo?
* To use it from the repo, you need to compile it and link it with your project. Do you want more information about that?

**Comment by felipeolvr** [comment]
yes, I want to... I was trying to run the project in vue that is in this repository, to see it working and see how to use its components

**Comment by julien-nc** [comment]
It does not run alone, you have to import it and use it somewhere in your code.

There is an example page in the repo. To see it in action, just compile the repo 
``` bash
npm ci ; npm run dev
```
and browse `examples/with-vue.html`

If you want to see how the example is done, interesting files are:
* examples/with-vue.html
* src/exampleVue.js
* src/views/ExampleApp.vue

**Comment by felipeolvr** [comment]
I understand, but I can't run the entire vue project in development mode? to see the components working on my localhost, so I can understand how everything works and implement it in my project

**Comment by julien-nc** [comment]
Like I said, check the mentioned files to see how the component can be used. It is actually used in src/views/ExampleApp.vue

**Comment by felipeolvr** [comment]
that's right, but I'm still not able to run the project, when I run npm run dev it returns the following webpack error


➜ nextcloud-webdav-filepicker (master) ✔ npm run dev

> nextcloud-webdav-filepicker@0.0.21 dev /Users/felipoliver/Documents/projetos/nextcloud-webdav-filepicker
> NODE_ENV=development webpack --progress --config webpack.js

sh: webpack: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! nextcloud-webdav-filepicker@0.0.21 dev: `NODE_ENV=development webpack --progress --config webpack.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the nextcloud-webdav-filepicker@0.0.21 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/felipoliver/.npm/_logs/2022-01-13T14_24_31_351Z-debug.log

**Comment by julien-nc** [comment]
Did you run `npm ci` before?

**Comment by felipeolvr** [comment]
yes

**Comment by felipeolvr** [comment]
➜ nextcloud-webdav-filepicker (master) ✔ npm ci

> core-js@3.20.0 postinstall /Users/felipoliver/Documents/projetos/nextcloud-webdav-filepicker/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@2.6.12 postinstall /Users/felipoliver/Documents/projetos/nextcloud-webdav-filepicker/node_modules/@babel/polyfill/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.6.1 postinstall /Users/felipoliver/Documents/projetos/nextcloud-webdav-filepicker/node_modules/@nextcloud/browser-storage/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.6.4 postinstall /Users/felipoliver/Documents/projetos/nextcloud-webdav-filepicker/node_modules/@nextcloud/moment/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

added 348 packages in 4.949s

**Comment by julien-nc** [comment]
What's your operating system, npm version and node version?
I probably won't be able to help you as you're supposed to get webpack as a dependency to "@nextcloud/webpack-vue-config" which is a devDependency of the project.
Is there a "webpack" directory in the "node_modules" directory created after you run `npm ci`?

**Comment by felipeolvr** [comment]
I'm using mac os system, node 14.17 and npm 6.14 and I didn't find the webpack folder in node_modules, so I have to install this dependency apart?

**Comment by julien-nc** [comment]
I would not recommend to start doing things manually as it's probably nerver going to work :wink:.
I would recommend to try updating npm to the latest available:
```
npm install -g npm
```
Then try `npm ci ; npm run dev` again.

**Comment by felipeolvr** [comment]
➜ nextcloud-filepicker (master) ✔ npm run dev

> nextcloud-webdav-filepicker@0.0.21 dev
> NODE_ENV=development webpack --progress --config webpack.js

Building nextcloud-webdav-filepicker 0.0.21 

assets by path *.js 7.45 MiB
  asset exampleVue.js 3.74 MiB [emitted] (name: exampleVue) 1 related asset
  asset filePickerWrapper.js 3.71 MiB [emitted] (name: wrapper) 1 related asset
assets by path Components/*.js 6.75 MiB
  asset Components/NcWebdavFilePicker.js 3.71 MiB [emitted] (name: mainComponent) 1 related asset
  asset Components/FilePicker.js 3.04 MiB [emitted] (name: filePickerComponent) 1 related asset
webpack 5.65.0 compiled successfully in 9056 ms

**Comment by felipeolvr** [comment]
now it worked

**Comment by felipeolvr** [comment]
now how do i see it in my browser, on localhost ?

**Comment by julien-nc** [comment]
You can now blame apple for including a very old npm in their os :wink:.

If you have a local webserver, place the project somewhere in your web root.
You can also simply browse the file (with `file://`) but the component won't be able to make the WebDav requests due to browsers security restrictions.

**Comment by felipeolvr** [comment]
this apple... so npm run dev or npm run build generate the project in html to run right, it doesn't run in vue dev mode by cli to view in browser as localhost:8000 or something

**Comment by julien-nc** [comment]
You can an entry the to the scripts in package.json if you want to deploy a small dev webserver. It's not done yet.

**Comment by felipeolvr** [comment]
i will try this...

"scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },

**Comment by felipeolvr** [comment]
don`t work

**Comment by julien-nc** [comment]
``` bash
# remove you changes
git checkout .
# get latest master
git pull origin master
npm ci
npm run serve
```

**Comment by felipeolvr** [comment]
thanks, working for me... now i'm trying to install in my project, and in the console i get these errors

Vue warn]: Property "$createElement" was accessed during render but is not defined on instance. 
  at <NcWebdavFilePicker nc-url="https://my.nextcloud.org" > 
  at <FilePicker> 
  at <QPage class="flex flex-center" > 
  at <PageIndex onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView> 
  at <QPageContainer> 
  at <QLayout view="lHh Lpr lFf" > 
  at <MainLayout onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView> 
  at <App>

**Comment by felipeolvr** [comment]
Hello, I'm trying to run the html and javascript version in my project in vue, and it's almost working, but it doesn't open the modal with filepicker. Do you have any suggestions?

**Comment by felipeolvr** [comment]
I managed to run the project in vue
