### ISSUE TITLE
File picker not working

### ISSUE THREAD

**Issue by varuncomp** [eneiluj/nextcloud-webdav-filepicker#3]
Hi,

I've tried 2 ways of getting the NextCoud file picker to work, but it appears that it doesn't seem to work.

Option 1 : 
Tried https://eneiluj.github.io/nextcloud-webdav-filepicker/examples/without-vue.html and https://eneiluj.github.io/nextcloud-webdav-filepicker/examples/with-vue.html

![Screenshot 2022-03-23 at 9 50 44 AM](https://user-images.githubusercontent.com/40627855/159623281-3f6196c9-60f4-4bef-9c6a-dfefd7c23bd2.png)

Option 2: Tried with a sample html/js app

Though I have provided nextCloud URL to be non-local host - https://ncloud.stark-online.shop - The file picker login flow is assuming that the webAppPassword app is present in localhost - see the screenshot

And just to clarify, webApppassword is installed on nextcloud server + the localhost domains are set as whitelisted origins.

![Screenshot 2022-03-23 at 9 52 13 AM](https://user-images.githubusercontent.com/40627855/159623420-3b6e9e58-4617-4c1b-9d88-ce81f92cf01e.png)

![Screenshot 2022-03-23 at 9 34 58 AM](https://user-images.githubusercontent.com/40627855/159623109-2d1902c3-9a0c-4741-b372-3af1da5f42ce.png)

Sample code : 

<script src = "../node_modules/nextcloud-webdav-filepicker/js/filePickerWrapper.js"></script>

<div id="mount_point"></div>
<script>
	// when the page is loaded
	document.addEventListener('DOMContentLoaded', (event) => {
		const appUrl = "https://ncloud.stark-online.shop/index.php/apps/webapppassword";
		// create and mount the component
		
		const filepicker = window.createFilePicker('mount_point', 'https://ncloud.stark-online.shop')
		 

		//let wnd = window.open(appUrl + "?target-origin=" + encodeURIComponent(window.location.href), "Nextcloud Login",
          //  "width=400,height=400,menubar=no,scrollbars=no,status=no,titlebar=no,toolbar=no");

		filepicker.getFilesPath()

		// listen to events coming from the component
		document.addEventListener('get-files-path', (e) => {
			console.debug('received "get-files-path" event')
			console.debug(e.detail.selection)
			e.detail.selection.forEach((path) => {
				console.debug(path)
			})
		})
	})
</script>

**Comment by julien-nc** [comment]
Hey,

For the `https://eneiluj.github.io/*` demo pages, the webapppassword auth method was disabled. It's now fixed. I just tried with one of my test servers, webapppassword login flow is used and works if you don't provide any login/password in those demo pages.

For your option 2. You passed a string instead of an Object to the wrapper function.
Check how it's used in the example page:
https://github.com/eneiluj/nextcloud-webdav-filepicker/blob/4d1e33c76c2b47a49fda7b0d18b807e97315f9ad/examples/without-vue.html#L104-L136
Only the url key is mandatory. So for you, this should work:
``` javascript
const filepicker = window.createFilePicker('mount_point', { url: 'https://ncloud.stark-online.shop' })
```

Any better?

**Comment by varuncomp** [comment]
Hey, thanks for the swift response!

Option 1 still doesnt work for me.

Although, i will make the changes suggested for Option 2 and test it out.

Thanks again!

- Varun

**Comment by webermax** [comment]
This filepicker is awesome!

There's a small bug with the demo which works only by injecting custom domains via url parameter, e.g.:

https://eneiluj.github.io/nextcloud-webdav-filepicker/examples/without-vue.html?url=https://my-domain.tld

(**?url=https://my-domain.tld**)
